language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
  - 5.0

before_install:

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli

script:
  - grunt
